Rs 55 gmail
FedAGcom/Recruitment-System pull request #59
Opened 2022-06-16 09:39 UTC by Barsu4ello

Добавлено логировние и изменены настройки почты для отправки с почтового ящика gmail

2022-06-17 10:41 UTC, Aleksandr-Gurin requested changes

2022-06-17 10:41 UTC, Aleksandr-Gurin commented on src/main/resources/application.properties
> +#spring.jpa.show-sql=true ??????????????? ????? ?? ???? ??????? ?????? ? ???????
забыл коммент

2022-06-17 10:48 UTC, Barsu4ello commented on src/main/resources/application.properties
> +#spring.jpa.show-sql=true ??????????????? ????? ?? ???? ??????? ?????? ? ???????
Видимо проперти на русском не коментится, поправлю в следующем пр

2022-06-17 10:52 UTC, Barsu4ello commented on src/main/resources/application.properties
> +#spring.jpa.show-sql=true ??????????????? ????? ?? ???? ??????? ?????? ? ???????
Поправил.

2022-06-20 11:49 UTC, Aleksandr-Gurin approved these changes

2022-06-20 11:49 UTC, merged